---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/appsvc-rhtap/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-trimmed
